<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
 <ServerGarbageCollection>false</ServerGarbageCollection>
<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>


    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.3" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="System.Device.Gpio" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\" />
  </ItemGroup>

</Project>
